
-- Clear existing sample intents and add comprehensive new ones
DELETE FROM public.chatbot_intents WHERE intent_key IN (
  'find_shelter', 'get_food', 'get_healthcare', 'report_abuse', 
  'emergency_contact', 'how_glo_works', 'language_support'
);

-- Insert enhanced and new intents with warm, supportive responses
INSERT INTO public.chatbot_intents (category, intent_key, keywords, response_template) VALUES

-- Enhanced Shelter Intent with emotional keywords
('basic_service', 'shelter_need', 
 '{"english": ["shelter", "place to sleep", "sleep tonight", "homeless", "cold", "nowhere to go", "need accommodation", "housing", "room", "bed"], "swahili": ["mahali pa kulala", "kulala leo usiku", "makazi", "baridi", "sina pa kulala", "nyumba", "chumba"], "sheng": ["base", "place ya kulala", "kulala", "niko baridi"], "arabic": ["مأوى", "مكان للنوم", "بارد", "بيت"]}',
 '{"english": "I''m so sorry you''re going through this. You deserve a safe, warm place to sleep. Let me help you find emergency shelter near you right away. Can you tell me your location or the area you''re in? You''re not alone in this.", "swahili": "Pole sana kwa hali hii ngumu. Unastahili mahali salama pa kulala. Niruhusu nikusaidie kupata makazi ya dharura karibu nawe. Unaweza kuniambia uko wapi? Haumo peke yako.", "sheng": "Pole sana bro. Haupaswa kulala nje. Nitakusort na place ya emergency karibu nawe. Niambie tu uko area gani? Tutakusaidia.", "arabic": "أنا آسف جداً لما تمرين به. تستحقين مكاناً آمناً ودافئاً للنوم. دعيني أساعدك في العثور على مأوى طارئ بالقرب منك. هل يمكنك إخباري بموقعك؟"}'),

-- Enhanced Food Intent with desperation indicators
('basic_service', 'food_need', 
 '{"english": ["food", "hungry", "starving", "eat", "meal", "nothing to eat", "no money for food", "feed my children", "nutrition"], "swahili": ["chakula", "njaa", "nina njaa", "kula", "mlo", "sina chakula", "sina pesa ya chakula", "kulisha watoto"], "sheng": ["food", "njaa", "dishi", "kula", "starve"], "arabic": ["طعام", "جوعان", "أكل", "وجبة", "أطفال جوعى"]}',
 '{"english": "I understand how hard it is to go without food, especially when you have children depending on you. Let me find food assistance near you right now. Can you share your location so I can connect you with the closest food bank or meal program? Help is available today.", "swahili": "Naelewa jinsi ni ngumu kukosa chakula, hasa ukiwa na watoto wanaotegemea wewe. Niruhusu nikutafutie msaada wa chakula karibu nawe sasa. Unaweza kushare location yako ili niweze kukuunganisha na chakula cha karibu? Msaada unapatikana leo.", "sheng": "Najua ni hard kukosa food, especially na watoto. Nitakutafutia food assistance karibu nawe sasa. Share location yako nikuconnect na food bank ya karibu. Tutakusaidia leo.", "arabic": "أفهم كم هو صعب البقاء دون طعام، خاصة عندما يعتمد عليك الأطفال. دعيني أجد مساعدة غذائية بالقرب منك الآن. هل يمكنك مشاركة موقعك؟"}'),

-- Enhanced Healthcare Intent
('healthcare', 'medical_need', 
 '{"english": ["doctor", "medical help", "sick", "health", "clinic", "hospital", "medicine", "treatment", "pregnant", "child sick", "pain"], "swahili": ["daktari", "mgonjwa", "afya", "kliniki", "hospitali", "dawa", "matibabu", "mjamzito", "mtoto mgonjwa", "maumivu"], "sheng": ["doki", "sick", "medical", "clinic", "dawa"], "arabic": ["طبيب", "مريض", "صحة", "عيادة", "مستشفى", "دواء", "حامل"]}',
 '{"english": "Your health and your family''s health are so important. I''m here to help you find medical care that you can access. Whether it''s for you or your children, let me connect you with healthcare services nearby. Can you tell me what kind of medical help you need and your location?", "swahili": "Afya yako na ya familia yako ni muhimu sana. Niko hapa kukusaidia kupata huduma za afya. Iwe ni kwa ajili yako au watoto wako, niruhusu nikuunganishe na huduma za afya za karibu. Unaweza kuniambia unahitaji aina gani ya msaada wa kiafya na uko wapi?", "sheng": "Health yako na ya watoto ni important. Nitakuconnect na healthcare services za karibu. Niambie unahitaji medical help gani na uko wapi?", "arabic": "صحتك وصحة عائلتك مهمة جداً. أنا هنا لمساعدتك في العثور على رعاية طبية يمكنك الوصول إليها. دعيني أربطك بخدمات الرعاية الصحية القريبة."}'),

-- New Mental Health Support Intent
('mental_health', 'emotional_support', 
 '{"english": ["overwhelmed", "depressed", "anxious", "stressed", "can''t cope", "feel down", "need someone to talk", "mental health", "counseling", "therapy"], "swahili": ["nimechoka", "nina stress", "hali mbaya", "sitaki", "nahitaji mtu wa kuongea", "afya ya akili"], "sheng": ["niko down", "stressed", "niko low", "need kuongea", "mental"], "arabic": ["مرهق", "مكتئب", "قلق", "لا أستطيع التأقلم", "أحتاج للحديث"]}',
 '{"english": "I''m here for you, and what you''re feeling is completely valid. It takes so much strength to reach out. I can connect you with a counselor who understands what you''re going through and will listen without judgment. Would you like me to find mental health support near you? You don''t have to face this alone.", "swahili": "Niko hapa kwa ajili yako, na unachohisi ni halali kabisa. Inahitaji nguvu kubwa kuomba msaada. Naweza kukuunganisha na mshauri anayeelewa unachopitia na atakusikiliza bila kuhukumu. Je, ungependa nikupatie msaada wa afya ya akili karibu nawe? Huna haja ya kupambana na hili peke yako.", "sheng": "Niko hapa for you, na vile unafeel ni sawa kabisa. Nitakuconnect na counselor atakayeeelewa situation yako. Hutakuwa peke yako kwa hii.", "arabic": "أنا هنا من أجلك، وما تشعرين به طبيعي تماماً. يمكنني ربطك بمستشار يفهم ما تمرين به. لست وحدك في هذا."}'),

-- New Job/Employment Support Intent
('employment', 'job_support', 
 '{"english": ["job", "work", "employment", "income", "money", "support my family", "skills training", "interview", "CV", "resume"], "swahili": ["kazi", "ajira", "mapato", "pesa", "kusaidia familia", "mafunzo", "mahojiano"], "sheng": ["job", "kazi", "work", "income", "pesa", "hustle"], "arabic": ["وظيفة", "عمل", "دخل", "نقود", "إعالة العائلة", "تدريب"]}',
 '{"english": "I understand how important it is to have stable income to support yourself and your family. You have valuable skills, and I''m here to help you find opportunities. Let me check what jobs and training programs are available near you. We also offer help with CVs and interview preparation. What kind of work interests you?", "swahili": "Naelewa jinsi ni muhimu kuwa na kipato cha kudumu ili ujitegemee na kusaidia familia yako. Una ujuzi wa thamani, na niko hapa kukusaidia kupata fursa. Niruhusu niangalie kazi na mipango ya mafunzo zilizopo karibu nawe. Pia tunatoa msaada wa CV na maandalizi ya mahojiano. Ni aina gani ya kazi unayoipenda?", "sheng": "Najua ni important kuwa na stable income ya kusupport familia. Una skills za value, nitakucheki opportunities za karibu. Tunahelp na CV na interview prep pia. Unapenda aina gani ya job?", "arabic": "أفهم مدى أهمية الحصول على دخل مستقر لإعالة نفسك وعائلتك. لديك مهارات قيّمة، وأنا هنا لمساعدتك في العثور على الفرص."}'),

-- New Location/Navigation Help Intent
('support', 'location_help', 
 '{"english": ["don''t know where I am", "lost", "can''t find", "where am I", "location", "directions", "how to get to"], "swahili": ["sijui niko wapi", "nimepotea", "siwezi kupata", "niko wapi", "mahali", "mwelekeo"], "sheng": ["niko lost", "sijui place", "nimepotea", "directions"], "arabic": ["لا أعرف أين أنا", "ضائع", "لا أستطيع العثور", "اتجاهات"]}',
 '{"english": "That''s okay, don''t worry. It happens, and we''ll figure this out together. If you can safely turn on location sharing, that would help me guide you. Or if you prefer, you can describe what you see around you - any buildings, signs, or landmarks. I''m here to help you get to where you need to go safely.", "swahili": "Sio shida, usiwe na wasiwasi. Inatokea, na tutamaliza hii pamoja. Kama unaweza kufungua location sharing kwa usalama, hiyo itanisaidia kukuongoza. Au kama unapendelea, unaweza kueleza unachoona karibu nawe - majengo yoyote, alama, au mahali maalum. Niko hapa kukusaidia kufika mahali unapohitaji kwa usalama.", "sheng": "Hakuna shida bro, sitasema stress. Kama unaweza turn on location sharing, itanisaidia. Ama describe tu vile unaona - mabuildings ama signs za karibu. Nitakuguide safe.", "arabic": "لا بأس، لا تقلقي. هذا يحدث، وسنحل الأمر معاً. إذا كان بإمكانك تشغيل مشاركة الموقع بأمان، فسيساعدني ذلك في إرشادك."}'),

-- New App Guidance Intent
('platform', 'app_guidance', 
 '{"english": ["how to use", "how does this work", "what is Glo", "help using app", "navigate", "tutorial", "instructions"], "swahili": ["jinsi ya kutumia", "hii inafanyaje kazi", "Glo ni nini", "msaada wa kutumia", "mwongozo"], "sheng": ["nianze aje", "hii system inafanya nini", "how to use", "mwongozo"], "arabic": ["كيف أستخدم", "كيف يعمل هذا", "ما هو جلو", "مساعدة في الاستخدام"]}',
 '{"english": "Welcome to Glo! I''m so glad you''re here. This is a safe space designed just for you. You can tell me what kind of help you need - like shelter, food, healthcare, or job support - and I''ll connect you with local services. You can also use the quick buttons below for common needs. Everything here is confidential and designed to keep you safe. What would you like help with today?", "swahili": "Karibu Glo! Nimefurahi sana uko hapa. Hii ni mazingira salama yaliyotengenezwa kwa ajili yako. Unaweza kuniambia aina ya msaada unaohitaji - kama makazi, chakula, afya, au msaada wa kazi - na nitakuunganisha na huduma za mitaani. Unaweza pia kutumia vitufe vya haraka hapa chini kwa mahitaji ya kawaida. Kila kitu hapa ni siri na kimeundwa kukuhifadhi salama. Ungependa msaada wa nini leo?", "sheng": "Karibu Glo! Happy uko hapa. Hii ni safe space yetu. Niambie tu unahitaji msaada gani - shelter, food, healthcare, ama job support - nitakuconnect na services za local. Una quick buttons pia za common needs. Kila kitu hapa ni confidential na designed kukuprotect. Utaka help ya nini leo?", "arabic": "مرحباً بك في جلو! أنا سعيد جداً لوجودك هنا. هذا مكان آمن مصمم خصيصاً لك. يمكنك إخباري بنوع المساعدة التي تحتاجينها وسأربطك بالخدمات المحلية."}'),

-- Enhanced Emergency Intent with fear-based phrases
('emergency', 'immediate_danger', 
 '{"english": ["help", "danger", "emergency", "urgent", "scared", "afraid", "in trouble", "need help now", "call police", "violence", "abuse"], "swahili": ["msaada", "hatari", "dharura", "haraka", "ninaogopa", "nina hofu", "niko shidani", "nahitaji msaada sasa", "piga polisi"], "sheng": ["help", "nisaidie", "niko kwa shida", "emergency", "haraka sana", "danger"], "arabic": ["مساعدة", "خطر", "طوارئ", "عاجل", "خائف", "في مشكلة", "اتصل بالشرطة"]}',
 '{"english": "🚨 I''m here with you. If you''re in immediate danger right now, please call 911 or go to the nearest police station immediately. Your safety is the most important thing. If you can''t call, there''s an emergency button in this app that can help. I can also connect you with our 24/7 crisis support line. Are you somewhere safe right now?", "swahili": "🚨 Niko hapa pamoja nawe. Kama uko katika hatari ya mara moja sasa hivi, tafadhali piga 911 au uende kituo cha polisi cha karibu mara moja. Usalama wako ndio muhimu zaidi. Kama huwezi kupiga simu, kuna kitufe cha dharura katika app hii kinachoweza kusaidia. Pia naweza kukuunganisha na mstari wetu wa msaada wa saa 24/7. Je, uko mahali salama sasa hivi?", "sheng": "🚨 Niko hapa na wewe. Kama uko kwa immediate danger sasa, piga 911 ama uende police station ya karibu haraka. Safety yako ni priority. Kama hauwezi call, kuna emergency button kwa hii app. Uko safe sasa?", "arabic": "🚨 أنا هنا معك. إذا كنت في خطر فوري الآن، يرجى الاتصال بالرقم 911 أو التوجه لأقرب مركز شرطة فوراً. سلامتك هي الأهم. هل أنت في مكان آمن الآن؟"}');
