// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fznhhkxwzqipwfwihwqr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ6bmhoa3h3enFpcHdmd2lod3FyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1NjM2MDYsImV4cCI6MjA2NTEzOTYwNn0.pf2kXjz8hnXbXpC-X3aEahv3ge-mAES0dVoMgeSrRAY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);